### ISSUE TITLE
Les mots de passe ne sont pas chiffrés!

### ISSUE THREAD

**Issue by SkyzohKey** [Ogromny/PastaBin#1]
Tu peux pas ne pas chiffrer les mots de passe. C'est une faille de sécurité epic. x)
Le problème ici c'est que si tu chiffres le mot de passe, tu ne peux plus déchiffrer.
La solution est donc de ne **PAS** sauvegarder les mots de passe dans la db, laisse le soin à l'utilisateur de le mémoriser/sauvegarder. Comme ça pas de problème si quelqu'un hack ta DB (ou si la ptn de NSA d'sa mère pwned ton serveur)

**Comment by Ogromny** [comment]
ouais mais comment je fais pour check après le password ?

**Comment by Ogromny** [comment]
Fait !
